// Generated by CoffeeScript 1.10.0
(function() {
  var enemylife, flag, myhand, mylife;

  $(function() {
    app.setup();
    return app.setBind();
  });

  flag = void 0;

  mylife = void 0;

  enemylife = void 0;

  myhand = void 0;

  window.app = {
    setup: function() {
      flag = -1;
      $('#AnimeOutput').text('じゃんけんゲーム');
      $('#Output').text('スタートをおしてね');
      this.changeLife(3, 0);
      return this.changeLife(3, 1);
    },
    setBind: function() {
      $('#start').bind('click', (function(_this) {
        return function() {
          if (flag === -1) {
            mylife = 3;
            _this.changeLife(mylife, 0);
            enemylife = 3;
            _this.changeLife(enemylife, 1);
            $(".handBox").html('');
            $('.window').text(' ');
            $('#Output').text('スタート');
            $('#AnimeOutput').html("<p class=\"movetxt\">じゃんけんぽん</p>");
            _this.textAnime('.movetxt');
            return _this.flagChange(1);
          }
        };
      })(this));
      $('#replay').bind('click', (function(_this) {
        return function() {
          if (flag === 0) {
            $('#Output').text('もう１回');
            $(".handBox").html('');
            $('#AnimeOutput').html("<p class=\"movetxt\">じゃんけんぽん</p>");
            _this.textAnime('.movetxt');
            return _this.flagChange(1);
          }
        };
      })(this));
      $('#gu').bind('click', (function(_this) {
        return function() {
          return _this.printMyHand(0);
        };
      })(this));
      $('#choki').bind('click', (function(_this) {
        return function() {
          return _this.printMyHand(1);
        };
      })(this));
      return $('#pa').bind('click', (function(_this) {
        return function() {
          return _this.printMyHand(2);
        };
      })(this));
    },
    game: (function(_this) {
      return function(myhand) {
        var check, enemyhand;
        enemyhand = _.random(2);
        app.printHand(enemyhand, 1);
        check = enemyhand - myhand;
        if (check < 0) {
          check += 3;
        }
        if (check === 0) {
          flag = 2;
          $('#Output').text('引き分け');
          $('#AnimeOutput').html("<p class=\"movetxt\">あいこでしょ</p>");
          app.textAnime('.movetxt');
          app.flagChange(1);
        } else if (check === 1) {
          $('#Output').text('勝ち');
          enemylife--;
          app.changeLife(enemylife, 1);
          flag = 0;
        } else {
          $('#Output').text('負け');
          mylife--;
          app.changeLife(mylife, 0);
          flag = 0;
        }
        if (!(mylife && enemylife)) {
          $('#AnimeOutput').text('スタートをおすともう１回できるよ！');
          flag = -1;
        }
        if (mylife === 0) {
          return $('#LifeOutput').text('ライフポイント0であなたの負け');
        } else if (enemylife === 0) {
          return $('#LifeOutput').text('相手が倒れました！あなたの勝ち');
        }
      };
    })(this),
    changeLife: (function(_this) {
      return function(life, code) {
        var html;
        html = '';
        return _.each([1, 2, 3], function(i) {
          var id_type, image_type;
          if (life - i >= 0) {
            image_type = 'on';
          } else {
            image_type = 'off';
          }
          if (code === 0) {
            id_type = 'my';
          } else {
            id_type = 'enemy';
          }
          html += "<img src=\"image/redheart_" + image_type + ".png\" id=\"" + id_type + "Life" + i + "\" class=\"" + id_type + "Life\" alt=\"\" width=\"70\"/>";
          return $("#" + id_type + "LifeBox").html(html);
        });
      };
    })(this),
    printHand: (function(_this) {
      return function(hand, code) {
        var html, id_type, image_type;
        html = '';
        if (hand === 0) {
          image_type = 'gu';
        } else if (hand === 1) {
          image_type = 'choki';
        } else {
          image_type = 'pa';
        }
        if (code === 0) {
          id_type = 'my';
        } else {
          id_type = 'enemy';
        }
        html += "<img src=\"image/" + image_type + ".jpg\" id=\"box" + id_type + "hand\" class=\"" + id_type + "hand\" alt=\"\" width=\"150\"/>";
        return $("#" + id_type + "handBox").html(html);
      };
    })(this),
    printMyHand: (function(_this) {
      return function(hand) {
        if (flag === 1) {
          myhand = hand;
          app.printHand(myhand, 0);
          $('#AnimeOutput').text('もう１回 する？');
          return app.game(myhand);
        }
      };
    })(this),
    textAnime: function(pos) {
      return $(pos).textillate({
        loop: false,
        minDisplayTime: 2000,
        initialDelay: 0,
        autoStart: true,
        "in": {
          effect: 'BounceInDown',
          delayScale: 1.5,
          delay: 50,
          sync: false,
          shuffle: false
        }
      });
    },
    flagChange: function(fg) {
      return setTimeout(function() {
        return flag = fg;
      }, 1500);
    }
  };

}).call(this);
